### PR TITLE
Added KSP Stock Tags to Parts, fixed some Typos

### PR DESCRIPTION
**Pull request by sparkybear**
All parts in the B9_Aerospace and B9_Aerospace_HX have had stock tags
added to them. Tags belong in the 'Part' heading of each part, outside
of any sub-headings. Tags are ordered alphabetically.

There were whites pace changes that were done automatically due to the editor i was using, but they should not have affected anything substantial.

### CODE REVIEW

**Comment by blowfishpro** [comment]
Looks good generally.

One thing I noticed is that there seems to be a bit of inconsistency as to which parts have the fuel tags applied to them ("(lf", "?lf", "?lfo", "liquid", "mono", "monopropellant", etc).  I'd like to have it so that any part with a subtype containing a particular fuel would have all the applicable tags for that fuel.  There are a couple of options there:

1. Just add the tags
2. Remove the fuel tags and I can do it programatically in B9PartSwitch.  This would guarantee consistency going forward.

**Comment by sparkybear** [comment]
Part of that was due to a few parts that had both structural and fueltank properties, with the fuel tank having multiple internal configurations that weren't limited to juts one type of fuel. that said, I can go through and add additional tags to those parts to make them more consistent.

**Comment by blowfishpro** [comment]
I think the best scenario is for every part to have the tags for each subtype.  I.e. if I'm searching for lfo, I want any part that _can_ contain LFO, not just the ones that contain it by default.  So I think it's fine for parts to have a mix of structural and tank tags.  Again, it is possible for me to add the fuel-specific tags programatically, but I'm not 100% sure that's the best option.

**Comment by sparkybear** [comment]
I think you're right. I'll go through and add additional fuel tags and try to establish a better standard for future parts. I can see a few issues if added problematically that would result in a lot of extra work to properly validate.

**Comment by sparkybear** [comment]
The changes have been added and I think they are automatically included in this pull request.

**Comment by blowfishpro** [comment]
Sorry to keep finding things, but I still see some issues:

* Not all the tanks have tags for all their fuels.  In particular, Monopropellant seems to be missing from many
* It looks like some of the HX tanks don't have any fuel tags at all
* Some of the HX hangars appear to have fuel tags even though they don't have any fuel options.

**Comment by sparkybear** [comment]
No worries, check one last time and then feel free to add whatever you feel is missing. Apologies for the wait and I hope I haven't taken up too much of your time through this,

**Comment by blowfishpro** [comment]
Merged manually with some squashing and a few fixes.  In retrospect maybe not such a good idea, but it's done.  Thanks for all the help.

**Comment by sparkybear** [comment]
No worries, hopefully wasn't too much extra work for you.

**Pull request closed without merging**
